### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FPS-86** [nabeky/a3_exile_lootbox#5]
Hey. You have a mistake in the script putSimpleobj.sqf

3164. 19:40:59 Error in expression <rel];
3168. 19:40:59   Error position: <_model, _tpos];
3170. 19:40:59   Error Undefined variable in expression: _model
3171. 19:40:59 File x\addons\a3_exile_lootbox\functions\putSimpleobj.sqf, line 33

**Comment by nabeky** [comment]
hi, maybe "CUP Terrains MOD object" in settings(default)

config.spf
plz delete lines(search "cup" word)

or

Canot use simpleobject.

**Comment by yukihito23** [comment]
It is mentioned in the readme that this add-on is developed to fit cup takistan map by default so if using default settings, it will require cup terrains core. If using on other map, you will have to customize the config.cpp yourself. Thus this is not a problem with the add-on function but rather your mistake in not configuring it correctly.
